# Generated by Django 2.2.3 on 2022-10-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_criação',
            new_name='data_criacao',
        ),
    ]
